### ISSUE TITLE
Container overflow issue in search

### ISSUE THREAD

**Issue by insomnia-creator** [JBChangelogs/JailbreakChangelogs#24]
https://github.com/user-attachments/assets/90d10992-503e-4a6f-808e-26b76bb55f20

Appears that the search container is overflowing in the website

**Comment by insomnia-creator** [comment]
Addendum: Using firefox version 131.0a1
![CleanShot 2024-09-03 at 07 38 22@2x](https://github.com/user-attachments/assets/17197cbb-5aaf-4acc-84a3-f3dbf9fefa2a)

Can confirm the issue is existent on other browsers too. Not a browser specific issue.

**Comment by JBChangelogs** [comment]
Thanks for pointing that out. Looking into it.
