### ISSUE TITLE
Trade Tracker

### ISSUE THREAD

**Issue by saM14GH** [JBChangelogs/JailbreakChangelogs#49]
Missing: ItemCustomization.WeaponSkin, in In tab - Trade Tracker. It would be really good if you added this tab.
Example:
![image](https://github.com/user-attachments/assets/b0b5c289-5f07-425e-b44c-45b52f56429e)

**Comment by JBChangelogs** [comment]
The dataset provided by Badimo doesn't include weapon skins, just the vehicle customisation items with the vehicles themselves.
